export interface Shipping {
  name: string;
  size: string;
  maxHeight: number;
  g: number;
  cost: number;
  isAnonymous?: boolean;
  available: {
    mercari: boolean;
    rakuma: boolean;
  };
}

export const shippings: Shipping[] = [
  {
    name: 'ミニレター',
    size: '郵便書簡',
    maxHeight: 1,
    g: 25,
    cost: 62,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型郵便',
    size: '縦23.5×横12',
    maxHeight: 1,
    g: 25,
    cost: 82,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型郵便',
    size: '縦23.5×横12',
    maxHeight: 1,
    g: 50,
    cost: 92,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格内',
    size: '縦34×横25',
    maxHeight: 3,
    g: 50,
    cost: 120,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格内',
    size: '縦34×横25',
    maxHeight: 3,
    g: 100,
    cost: 140,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'らくらくメルカリ便 ネコポス',
    size: '31.2×22.8cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 175,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパケット',
    size: '長辺34cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 179,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'ゆうメール',
    size: '34×25cm以内',
    maxHeight: 3,
    g: 150,
    cost: 180,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'クリックポスト',
    size: '34×25cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 198,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ネコポス',
    size: '31.2×22.8cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 200,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパケット',
    size: '3辺合計 60cm以内 長辺34cm',
    maxHeight: 3,
    g: 1000,
    cost: 200,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: '定型外郵便：規格外',
    size: '３辺合計90㎝以内・長辺60cm以内',
    maxHeight: 60,
    g: 50,
    cost: 200,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格内',
    size: '縦34×横25',
    maxHeight: 3,
    g: 150,
    cost: 205,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうメール',
    size: '34×25cm以内',
    maxHeight: 3,
    g: 250,
    cost: 215,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格外',
    size: '３辺合計90㎝以内',
    maxHeight: 60,
    g: 100,
    cost: 220,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうパケット',
    size: '３辺合計60cm以内',
    maxHeight: 1,
    g: 1000,
    cost: 250,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格内',
    size: '縦34×横25',
    maxHeight: 3,
    g: 250,
    cost: 250,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパケットポスト',
    size: '縦32.5cm x 横22.5cm',
    maxHeight: 3,
    g: 2000,
    cost: 265,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: '定型外郵便：規格外',
    size: '３辺合計90㎝以内',
    maxHeight: 60,
    g: 150,
    cost: 290,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうメール',
    size: '34×25cm以内',
    maxHeight: 3,
    g: 500,
    cost: 300,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうパケット',
    size: '３辺合計60cm以内',
    maxHeight: 2,
    g: 1000,
    cost: 310,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格外',
    size: '３辺合計90㎝以内',
    maxHeight: 60,
    g: 250,
    cost: 340,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうメール',
    size: '34×25cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 350,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうパケット',
    size: '３辺合計60cm以内',
    maxHeight: 3,
    g: 1000,
    cost: 360,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'レターパックライト',
    size: '34×24.8cm',
    maxHeight: 3,
    g: 4000,
    cost: 370,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: '定型外郵便：規格内',
    size: '縦34×横25',
    maxHeight: 3,
    g: 500,
    cost: 380,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパケットプラス(箱別)',
    size: '縦24×横17',
    maxHeight: 7,
    g: 2000,
    cost: 380,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパケットプラス',
    size: '24×17cm以内',
    maxHeight: 7,
    g: 2000,
    cost: 440,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパケットプラス(箱込)',
    size: '縦24×横17',
    maxHeight: 7,
    g: 2000,
    cost: 380 + 65,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便コンパクト',
    size: '縦25×横20',
    maxHeight: 5,
    g: 10000,
    cost: 450,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: '定型外郵便：規格外',
    size: '３辺合計90㎝以内',
    maxHeight: 60,
    g: 500,
    cost: 500,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'レターパックプラス',
    size: '34×24.8cm・厚さは入ればOK',
    maxHeight: 12,
    g: 4000,
    cost: 520,
    available: {
      mercari: true,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便コンパクト',
    size: '縦25×横20',
    maxHeight: 5,
    g: 100000,
    cost: 600,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパック 60サイズ',
    size: '3辺合計60cm以内',
    maxHeight: 60,
    g: 25000,
    cost: 700,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 60サイズ',
    size: '3辺合計60cm以内',
    maxHeight: 60,
    g: 2000,
    cost: 700,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 60サイズ',
    size: '3辺合計60cm以内',
    maxHeight: 60,
    g: 25000,
    cost: 700,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパック 80サイズ',
    size: '3辺合計80cm以内',
    maxHeight: 80,
    g: 25000,
    cost: 800,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 80サイズ',
    size: '3辺合計80cm以内',
    maxHeight: 80,
    g: 5000,
    cost: 800,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 60サイズ',
    size: '3辺合計60cm以内',
    maxHeight: 60,
    g: 2000,
    cost: 800,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 80サイズ',
    size: '3辺合計80cm以内',
    maxHeight: 80,
    g: 5000,
    cost: 900,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 80サイズ',
    size: '3辺合計80cm以内',
    maxHeight: 80,
    g: 25000,
    cost: 900,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'ゆうゆうメルカリ便 ゆうパック 100サイズ',
    size: '3辺合計100cm以内',
    maxHeight: 100,
    g: 25000,
    cost: 1000,
    isAnonymous: true,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 100サイズ',
    size: '3辺合計100cm以内',
    maxHeight: 100,
    g: 10000,
    cost: 1000,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 120サイズ',
    size: '3辺合計120cm以内',
    maxHeight: 120,
    g: 15000,
    cost: 1100,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 140サイズ',
    size: '3辺合計140cm以内',
    maxHeight: 140,
    g: 20000,
    cost: 1300,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'らくらくメルカリ便 宅急便 160サイズ',
    size: '3辺合計160cm以内',
    maxHeight: 160,
    g: 25000,
    cost: 1600,
    available: {
      mercari: true,
      rakuma: false,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 100サイズ',
    size: '3辺合計100cm以内',
    maxHeight: 100,
    g: 10000,
    cost: 1150,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 120サイズ',
    size: '3辺合計120cm以内',
    maxHeight: 120,
    g: 15000,
    cost: 1350,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 140サイズ',
    size: '3辺合計140cm以内',
    maxHeight: 140,
    g: 20000,
    cost: 1550,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 160サイズ',
    size: '3辺合計160cm以内',
    maxHeight: 160,
    g: 25000,
    cost: 1800,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 180サイズ',
    size: '3辺合計180cm以内',
    maxHeight: 180,
    g: 30000,
    cost: 2100,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック 宅急便 200サイズ',
    size: '3辺合計200cm以内',
    maxHeight: 200,
    g: 30000,
    cost: 2500,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 100サイズ',
    size: '3辺合計100cm以内',
    maxHeight: 100,
    g: 25000,
    cost: 1150,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 120サイズ',
    size: '3辺合計120cm以内',
    maxHeight: 120,
    g: 25000,
    cost: 1350,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 140サイズ',
    size: '3辺合計140cm以内',
    maxHeight: 140,
    g: 25000,
    cost: 1500,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 160サイズ',
    size: '3辺合計160cm以内',
    maxHeight: 160,
    g: 25000,
    cost: 1500,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
  {
    name: 'かんたんラクマパック ゆうパック 170サイズ',
    size: '3辺合計170cm以内',
    maxHeight: 170,
    g: 25000,
    cost: 1500,
    isAnonymous: true,
    available: {
      mercari: false,
      rakuma: true,
    },
  },
];
